FROM ubuntu/nginx:1.18-20.04_beta

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

#install nginx-agent
RUN apt-get update && apt-get install -y gnupg
RUN apt install curl -y
RUN curl -k https://192.168.1.8/install/nginx-agent > install.sh
RUN sh ./install.sh
RUN ./bin/nginx-agent &
#RUN apt -y install systemctl
#create service
